import { METAL_MAP_TINT, STONE_METALNESS, STONE_ROUGHNESS } from './metal';

export const SEALED_BLOCK_METALNESS = STONE_METALNESS;
export const SEALED_BLOCK_ROUGHNESS = STONE_ROUGHNESS;
export const SEALED_BLOCK_TINT = METAL_MAP_TINT;

export const SEALED_BLOCK_SURFACE = {
    color: SEALED_BLOCK_TINT,
    roughness: SEALED_BLOCK_ROUGHNESS,
    metalness: SEALED_BLOCK_METALNESS,
} as const;
