import { GRAPHITE_ALBEDO, GRAPHITE_METALNESS, GRAPHITE_ROUGHNESS } from './graphite';

export const SEALED_BLOCK_METALNESS = GRAPHITE_METALNESS;
export const SEALED_BLOCK_ROUGHNESS = GRAPHITE_ROUGHNESS;
export const SEALED_BLOCK_COLOR = GRAPHITE_ALBEDO;

export const SEALED_BLOCK_SURFACE = {
    color: SEALED_BLOCK_COLOR,
    roughness: SEALED_BLOCK_ROUGHNESS,
    metalness: SEALED_BLOCK_METALNESS,
} as const;
