import { METAL_MAP_TINT, METAL_METALNESS, METAL_ROUGHNESS } from './metal';

export const SEALED_BLOCK_METALNESS = METAL_METALNESS;
export const SEALED_BLOCK_ROUGHNESS = METAL_ROUGHNESS;
export const SEALED_BLOCK_TINT = METAL_MAP_TINT;

export const SEALED_BLOCK_SURFACE = {
    color: SEALED_BLOCK_TINT,
    roughness: SEALED_BLOCK_ROUGHNESS,
    metalness: SEALED_BLOCK_METALNESS,
} as const;
